# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import todo_app_pb2 as todo__app__pb2


class TodoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListAllTodos = channel.unary_unary(
                '/TodoService/ListAllTodos',
                request_serializer=todo__app__pb2.ListAllTodosRequest.SerializeToString,
                response_deserializer=todo__app__pb2.ListAllTodosResponse.FromString,
                )
        self.AddTodo = channel.unary_unary(
                '/TodoService/AddTodo',
                request_serializer=todo__app__pb2.Todo.SerializeToString,
                response_deserializer=todo__app__pb2.Todo.FromString,
                )
        self.DeleteTodo = channel.unary_unary(
                '/TodoService/DeleteTodo',
                request_serializer=todo__app__pb2.DeleteTodoRequest.SerializeToString,
                response_deserializer=todo__app__pb2.EmptyResponse.FromString,
                )
        self.EditTodo = channel.unary_unary(
                '/TodoService/EditTodo',
                request_serializer=todo__app__pb2.Todo.SerializeToString,
                response_deserializer=todo__app__pb2.Todo.FromString,
                )


class TodoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListAllTodos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddTodo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTodo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditTodo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TodoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListAllTodos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAllTodos,
                    request_deserializer=todo__app__pb2.ListAllTodosRequest.FromString,
                    response_serializer=todo__app__pb2.ListAllTodosResponse.SerializeToString,
            ),
            'AddTodo': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTodo,
                    request_deserializer=todo__app__pb2.Todo.FromString,
                    response_serializer=todo__app__pb2.Todo.SerializeToString,
            ),
            'DeleteTodo': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTodo,
                    request_deserializer=todo__app__pb2.DeleteTodoRequest.FromString,
                    response_serializer=todo__app__pb2.EmptyResponse.SerializeToString,
            ),
            'EditTodo': grpc.unary_unary_rpc_method_handler(
                    servicer.EditTodo,
                    request_deserializer=todo__app__pb2.Todo.FromString,
                    response_serializer=todo__app__pb2.Todo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TodoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TodoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListAllTodos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TodoService/ListAllTodos',
            todo__app__pb2.ListAllTodosRequest.SerializeToString,
            todo__app__pb2.ListAllTodosResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TodoService/AddTodo',
            todo__app__pb2.Todo.SerializeToString,
            todo__app__pb2.Todo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TodoService/DeleteTodo',
            todo__app__pb2.DeleteTodoRequest.SerializeToString,
            todo__app__pb2.EmptyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EditTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TodoService/EditTodo',
            todo__app__pb2.Todo.SerializeToString,
            todo__app__pb2.Todo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
